In [1]:
import numpy as np
%matplotlib notebook

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [11]:
matrixA = np.array([[2,4,-7],[3,-3,0],[1,7,5]])
matrixB = np.array([[2,4],[3,-3],[1,7]])
matrixC = np.array([[-1,1],[1,-1]])
matrixD = np.array([[2,0],[-3,6]])

1. Multiply $\bf{A}$ by 2.5 

In [12]:
matrixA = matrixA* 2.5
matrixA


array([[  5. ,  10. , -17.5],
       [  7.5,  -7.5,   0. ],
       [  2.5,  17.5,  12.5]])

2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [14]:
#dimensions of matrix not the same so can multiply
matrixCA = np.matmul(matrixC, matrixA)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [16]:
matrixCD = np.matmul(matrixC, matrixD)
print(matrixCD)
print('')
matrixDC = np.matmul(matrixD, matrixC)
print(matrixDC)
#not same result, matrix multiplication is not symmetrical

[[-5  6]
 [ 5 -6]]

[[-2  2]
 [ 9 -9]]


4. Find the transpose of $\bf{B}$

In [18]:
transB = matrixB.T
transB

array([[ 2,  3,  1],
       [ 4, -3,  7]])

5. Add $\bf{C} + \bf{D}$

In [20]:
matrixC_D = matrixC + matrixD
matrixC_D

array([[ 1,  1],
       [-2,  5]])

6. Compute the determinate of $\bf{C}$

In [22]:
detC = np.linalg.det(matrixC)
detC

0.0

7. Compute the determinate of $\bf{A}$

In [25]:
detA = np.linalg.det(matrixA)
detA

-4031.25